### ISSUE TITLE
大佬你好，能麻烦帮忙写个脚本吗，每次更新节点池配置的时候把节点名包含的Relay_和 Pool替换成空字符串

### ISSUE THREAD

**Issue by bubbleboy11** [yi-Xu-0100/cfw-scripts#139]

**Comment by yi-Xu-0100** [comment]
没看懂？节点名符合规则的，删除节点？

**Comment by bubbleboy11** [comment]
节点重命名
Relay_🇨🇳CN-🇹🇼TW_240 -> 🇹🇼TW_240
Pool_🇭🇰HK_705 -> 🇭🇰HK_705

**Comment by bubbleboy11** [comment]
https://proxies.bihai.cf/clash/proxies?c=HK,TW 例如这个节点池来源，把节点名的前缀给去掉

**Comment by yi-Xu-0100** [comment]
参考这个 https://github.com/Fndroid/clash_for_windows_pkg/issues/2934#issuecomment-1104608875
